version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastship-hu-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=fastship
      - DB_USERNAME=fastship
      - DB_PASSWORD=fastship
    networks:
      - fastship
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: fastship-hu-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - fastship
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: fastship-hu-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: fastship
      MYSQL_USER: fastship
      MYSQL_PASSWORD: fastship
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./base.sql:/docker-entrypoint-initdb.d/base.sql
    networks:
      - fastship

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fastship-hu-pma
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=fastship
      - PMA_PASSWORD=fastship
    depends_on:
      - mysql
    networks:
      - fastship

networks:
  fastship:
    driver: bridge

volumes:
  mysql_data: 